name: Magnolia
main: github.kairusds.Main
version: "1.2.0"
api: ["1.0.13"]
load: POSTWORLD
author: kairusds
description: "Life is an endless abyss with no purpose, we were all born to slave away for nothing and then die in complete agony."
website: "https://github.com/kairusds"

permissions:
  kairusds:
    default: false
    children:
      kairusds.message:
        default: false
        children:
          kairusds.message.device:
            description: "nanodesu"
            default: op
      kairusds.command:
        default: op
        children:
          kairusds.command.form:
            description: "doshite"
            default: op
          kairusds.command.htop:
            description: "sugoi"
            default: true
          kairusds.command.imagemap:
            description: "poggers"
            default: op
          kairusds.command.world:
            description: "nandayo"
            default: op