name: test
main: github.kairusds.Main
version: "1.1.0"
api: ["1.0.13"]
load: POSTWORLD
author: kairusds

permissions:
  test:
    default: false
    children:
      test.message:
        default: false
        children:
          test.message.device:
            description: "nanodesu"
            default: op
      test.command:
        default: false
        children:
          test.command.imagemap:
            description: "poggers"
            default: op
          test.command.htop:
            description: "sugoi"
            default: true