name: ${project.name}
main: github.kairusds.Main
version: ${project.version}
api: ["1.0.13"]
load: POSTWORLD
author: kairusds
description: ${project.description}
website: ${project.url}

permissions:
  kairusds:
    default: false
    children:
      kairusds.message:
        default: false
        children:
          kairusds.message.device:
            description: "nanodesu"
            default: op
      kairusds.command:
        default: op
        children:
          kairusds.command.form:
            description: "doshite"
            default: true
          kairusds.command.htop:
            description: "sugoi"
            default: true
          kairusds.command.imagemap:
            description: "poggers"
            default: op
          kairusds.command.settings:
            description: "ara"
            default: op
          kairusds.command.trainingdummy:
            default: "yamete"
            default: true
          kairusds.command.world:
            description: "nandayo"
            default: op